# https://prettier.io/docs/en/options.html
parser: typescript
printWidth: 120
tabWidth: 4
useTabs: false
semi: false
singleQuote: true
jsxSingleQuote: true
bracketSpacing: true
trailingComma: all
arrowParens: always
